-- Custom performance indexes added manually (not generated by Prisma schema diff)

-- Full-text search index on Product using GIN + tsvector for English stemming.
-- Enables fast `to_tsquery` searches across name and description columns.
CREATE INDEX IF NOT EXISTS idx_products_fts
  ON "Product" USING gin(to_tsvector('english', name || ' ' || description));

-- Composite index for listing a user's orders sorted newest-first.
-- Covers the common query: WHERE user_id = $1 ORDER BY created_at DESC.
CREATE INDEX IF NOT EXISTS idx_orders_user_created
  ON "Order" ("user_id", "created_at" DESC);

-- Composite index for fetching audit history per user, newest-first.
-- user_id is nullable (SetNull on user delete) so NULL entries are indexed too.
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_created
  ON "AuditLog" ("user_id", "created_at" DESC);
